### ISSUE TITLE
[PE-D][Tester B] Long group name cut off 

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103T-W15-2/tp#247]
![image.png](https://raw.githubusercontent.com/SimWPEric/ped/main/files/f1ce7a63-3339-45ac-a806-220338c157ad.png)

- Can be fixed by having a upper limit for character size 
- Or have a horizontal scroll functionality 

-------------
Labels: `severity.VeryLow` `type.FunctionalityBug`
original: SimWPEric/ped#13

**Comment by mingyuanc** [comment]
looking cute nereus
