### ISSUE TITLE
[PE-D][Tester D] Command succeeds format

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103T-W15-2/tp#253]
Did you miss it out here?
![Screenshot 2023-11-03 at 5.08.12 PM.png](https://raw.githubusercontent.com/jianyangg/ped/main/files/5d656f0a-74b1-4259-a46e-d6633200737a.png)

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: jianyangg/ped#11

**Comment by mingyuanc** [comment]
Mention that we are currently unable to edit tasks
